env:
  browser: true
  es2020: true
  node: true
  jest: true
extends:
  - "eslint:recommended"
  - "plugin:react/recommended"
  - "plugin:@typescript-eslint/recommended"
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2020
  sourceType: module
settings:
  react:
    version: detect
plugins:
  - react
  - "@typescript-eslint"
rules:
  no-undef: error
  "@typescript-eslint/interface-name-prefix":
    - error
    - prefixWithI: always
  "@typescript-eslint/member-delimiter-style":
    - error
    - multiline:
        delimiter: none
        requireLast: false
      singleline:
        delimiter: semi
        requireLast: false
